### ISSUE TITLE
Portable APP ?

### ISSUE THREAD

**Issue by ds2k5** [Fleex255/PolicyPlus#22]
Hi,
ist it possible to get a portalbe APP / one exe with all dependencies included ?
Thanks

**Comment by Fleex255** [comment]
Hmm, Policy Plus should already be portable - run `Policy Plus.exe` and you're good to go. If you're receiving error messages about a missing library, could you please post them?

**Comment by ds2k5** [comment]
but on a win7pe for example ist .net 4 missing an the app will not start

 


Gesendet: Montag, 17. September 2018 um 17:25 Uhr
Von: "Ben Nordick" <notifications@github.com>
An: Fleex255/PolicyPlus <PolicyPlus@noreply.github.com>
Cc: ds2k5 <dennisschneck@web.de>, Author <author@noreply.github.com>
Betreff: Re: [Fleex255/PolicyPlus] Portable APP ? (#22)


Hmm, Policy Plus should already be portable - run Policy Plus.exe and you're good to go. If you're receiving error messages about a missing library, could you please post them?

**Comment by Fleex255** [comment]
Ah, I see; thank you for clarifying. Unfortunately I can't package the .NET runtime into my program, but you can see [my answer here](https://superuser.com/a/1146939/380318) for how to add .NET to Windows PE.
