### ISSUE TITLE
Conflict/Fails on Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths

### ISSUE THREAD

**Issue by rugabunda** [Fleex255/PolicyPlus#23]
[Here is an image](https://i.ibb.co/4mvknvM/Policy-problem.png), on the left is PolicyPlus exported .pol, on the right is lgpo.exe export .pol of the same policy settings on the same machine.

**Comment by rugabunda** [comment]
I have not tried importing and don't know what will happen but its here for the developer if he is interested; using windows 10 1809 64 latest; did import sccm gpo also for 1803 pro non domain.

**Comment by Fleex255** [comment]
Thanks for the report! There is indeed a bug in list handling. Investigating now.

**Comment by Fleex255** [comment]
Should be fixed in https://github.com/Fleex255/PolicyPlus/commit/1af1f67ad7b8abae8c36303c09365edf63fde50d. The [dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) has been updated, please give it a try at your convenience.
