### ISSUE TITLE
Isnot in vb source

### ISSUE THREAD

**Issue by omegaminus** [Fleex255/PolicyPlus#24]
1) The IsNot operator cannot be used to compare expressions returned from the TypeOf operator. Instead, you must use the Not and Is operators. See 
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/isnot-operator#remarks
2) localization issue of .adml files (came across with de-AT where there is only de-DE subdir)
additional code in Function AddSingleAdmx as follows:
    Dim admlPath = Path.ChangeExtension(AdmxPath.Replace(fileTitle, LanguageCode & "\" & fileTitle), "adml")
--------- insert starts
    If Not File.Exists(admlPath) Then
      'try find another localization language flavor 
      For Each _locDirectory As String In Directory.GetDirectories(Path.GetDirectoryName(AdmxPath), LanguageCode.Split("-")(0) & "-*")
        admlPath = Path.Combine(_locDirectory, Path.ChangeExtension(fileTitle, "adml"))
        If File.Exists(admlPath) Then Exit For
      Next
    End If
----------- insert ends
    If Not File.Exists(admlPath) Then admlPath = Path.ChangeExtension(AdmxPath.Replace(fileTitle, "en-US\" & fileTitle), "adml")

**Comment by Fleex255** [comment]
Thanks for the feedback!

Regarding Part 1: The ability to use `IsNot` with `TypeOf` is [a relatively recent addition](https://visualstudiomagazine.com/Blogs/Tool-Tracker/2015/05/New-in-VB-14-IsNot-TypeOf.aspx) to the language, so it's possible that some documentation wasn't updated yet. [A different Microsoft Docs page](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/typeof-operator) shows the syntax.

Part 2 is implemented in https://github.com/Fleex255/PolicyPlus/commit/c38e7561a9f483079e924895e639cd7a5b8ec839. The [dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) has been updated - could you please try that and see if it works as you like?

**Comment by omegaminus** [comment]
Hi Ben, glad to help.
ad 1: The inability to use IsNot seemingly is an issue of vs2012 I used.
ad 2: looked at the source, should work (I'm not at the machine containing the source now), executable works!
Great job, thanks a lot
