### ISSUE TITLE
Change language?

### ISSUE THREAD

**Issue by EmilStenstrom** [Fleex255/PolicyPlus#25]
Hi!

I just tried your excellent app! It seems to work great, but I'm having trouble translating instructions from the internet in English, to my native language, Swedish. Is there a way to set Policy Plus to english, even though my Windows is set to a different language? Would help with following tutorials greatly!

**Comment by EmilStenstrom** [comment]
![bild](https://user-images.githubusercontent.com/224130/59979114-a03d5680-95e3-11e9-8f63-e619c28ac113.png)

**Comment by Fleex255** [comment]
I just implemented this in https://github.com/Fleex255/PolicyPlus/commit/14c0bf30db3472997b0562da3bdb7a80fe967c40. There is now a *Set ADML Language* option in the File menu that you can use to change the preferred language code. The code for US English is `en-US`. 

The [debug build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) has been updated. Please give that a try and let me know if there are any issues. Thanks!

**Comment by EmilStenstrom** [comment]
@Fleex255 Awesome! Much appreciated!

**Comment by EmilStenstrom** [comment]
It works great, thanks!
