### ISSUE TITLE
It is possible to refresh the policies at least on Windows 8.1 6.3.9600 Build 9600 Standard

### ISSUE THREAD

**Issue by Ceiridge** [Fleex255/PolicyPlus#26]
Hi,
what a great project!
I'm using this wonderful group policy editor instead of the one by microsoft, because I don't have it preinstalled. I could install it with some commands, but I prefer this one.
After downloading the admx files, I read in your README that invoking `RefreshPolicyEx` **wouldn't do anything on Home editions**.

I am not on a Pro edition, but I am able to refresh them with a simple self-written C++ program, that invokes **`RefreshPolicy`** (it refreshes the systemwide & user policies) and it works.

I've tried to disallow to change the wallpaper (user level) and I forced the control panel to always show the default profile picture for every user. After saving with the editor, nothing happened (of course) and after a policy refresh, it worked.
I was even able to change it back to the original state **without rebooting**.

I suggest you to check if maybe the method without `Ex` works on most/all Home versions.

**Comment by Fleex255** [comment]
Thanks for the tip! It looks like `RefreshPolicy`(`Ex`) notify applications of a policy change by broadcasting the [`WM_SETTINGCHANGE`](https://docs.microsoft.com/en-us/windows/desktop/winmsg/wm-settingchange) window message. They send the message even on Home editions despite not causing the application of POLs to the Registry. It seems to be somewhat dependent on the OS version - in my testing on Windows 10 the message wasn't always sent. 

https://github.com/Fleex255/PolicyPlus/commit/355c4bc466bf6ef529827ea1c4b93138a74a7027 makes Policy Plus directly broadcast the message on Home editions (and corrects the README). The [dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) has been updated.
