### ISSUE TITLE
Feasibility of adding the registry path & value name?

### ISSUE THREAD

**Issue by AltF5** [Fleex255/PolicyPlus#28]
Hi. It would be absolutely excellent to add this registry information  to the top or bottom of the description field for the policy setting. I see the keys are located in .admx files so it seems quite feasible to add this. I’m not sure how much work this could take, but I may consider looking into doing it myself in a  local copy of the code, but would be great if you too thought this may be a good idea!

**Comment by Fleex255** [comment]
Indeed, I also find it very useful to have the Registry information of policy settings. If you right-click a policy setting and choose Element Inspector, does the resulting dialog display the information you're looking for?
