### ISSUE TITLE
Cannot edit list parameter.

### ISSUE THREAD

**Issue by Ultrafeel** [Fleex255/PolicyPlus#29]
From here:
https://stackoverflow.com/a/38011386/5197544

"
> 1. Download Chrome group policy templates from:
> http://dl.google.com/dl/edgedl/chrome/policy/policy_templates.zip
> 2. open Policy Plus instead gpedit.msc 
> 3. Open [zip]\windows\admx\chrome.admx 
> 4. Expand User Configuration > Administrative Templates > Google Chrome > Extensions
> (Just "Google Chrome > Extensions")
> Double-click to open Configure "extension installation whitelist policy"
> Select Enabled, then click
> In the list, enter the ID(s) of the extensions :  for example, add : "nmgnihglilniboicepgjclfiageofdfj".
5. Press OK
6. Nothing changes.

**Comment by Fleex255** [comment]
Thank you for the report! I can confirm an incorrect policy state after trying to make the change you describe. Investigating now.

**Comment by Fleex255** [comment]
This should be fixed in https://github.com/Fleex255/PolicyPlus/commit/49cab9305b2652e100879f1948c0372d8d72f278 - does the [dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) work as expected?

**Comment by Ultrafeel** [comment]
Another problem: doesn't show last element from registry. I have three , 2 are shown

**Comment by Fleex255** [comment]
Hmm, I'm not quite sure what you mean, sorry. Are you seeing three values in the `ExtensionInstallWhitelist` key in the Registry Editor but only two in the Policy Plus list editor? 

If so, was the third entry manually added to the Registry? By default, Policy Plus operates on POL files (in Group Policy Objects), which take an extra step before appearing in the Registry; editing the Registry directly would not change the POL files that you examine with Policy Plus. If you have a POL open in Policy Plus, you can check what entries it contains with *File | Edit Raw POL*.

**Comment by Ultrafeel** [comment]
Didn't know that. So ,seems the issue is fixed.
