### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by HispidaBytes** [Fleex255/PolicyPlus#31]
The system requirements are missing on the documentation of the project.
Which version of .NET Framework is required and which version of Windows is supported ?

**Comment by Fleex255** [comment]
Thank you for the note! There is now a [system requirements](https://github.com/Fleex255/PolicyPlus#system-requirements) section in the README. Policy Plus requires .NET Framework 4.5 or newer, which requires Windows Vista or newer.
