### ISSUE TITLE
Tree contents shown in local language

### ISSUE THREAD

**Issue by gh658804** [Fleex255/PolicyPlus#32]
On Windows 7 on which i have tried it, the contents of the tree are displayed in my native language (which i find confusing), even though the version of Windows i have is English. It would be nice if there was an easy way to change that (a menu option perhaps).

**Comment by Fleex255** [comment]
I apologize for not seeing this issue earlier!

This option exists: *File | Set ADML Language*. You can change it to `en-US` to use English language resources.
