### ISSUE TITLE
So, does it work on Home? If so, identify which policies successfully applied, after applying

### ISSUE THREAD

**Issue by reelism** [Fleex255/PolicyPlus#33]
Reading through re: Home, and wholly unclear re:

> downloaded from Microsoft and installed with Help | Acquire ADMX Files.
> The RefreshPolicyEx native function has reduced functionality on editions without full Group Policy infrastructure, so while Policy Plus can edit the local GPO and apply the changes to the Registry, a reboot or logon/logoff cycle is required for some policy changes to take effect.
> While the UI allows the creation and editing of per-user GPOs, their settings are ignored by these limited editions of Windows. Edit per-user Registry hives instead.

The end reads like: Policy Plus, after applying the ADMX update doesn't work on Home, yet: 
>. . . edit the local GPO and apply the changes to the Registry, a reboot or logon/logoff cycle is required for some policy changes to take effect.

Sounds like, after updating and applying ADMX, the changes that are available ARE affected on Home. As an aside, this seems most useful (made for?) home, where Group Policies are not available.

Can you clarify?

If it's uncertain whether it's been applied, would be good to have a function to check what settings have been applied, even if only after logout/restart.

**Comment by Fleex255** [comment]
Thanks for asking for clarification! This is a bit confusing, sorry.

Yes, Policy Plus is generally designed for and works on Home editions. When you modify the local system-wide Group Policy Objects (either User or Computer section) on Home, Policy Plus will apply the changes to the appropriate Registry hive as well to account for the lack of Group Policy infrastructure on that system. 

Confusingly, "per-user GPOs" are a somewhat different thing than the system-wide User GPO. These are rarely useful on home machines and Policy Plus cannot currently apply them. You can achieve the same effect, however, by using Policy Plus to manipulate a "user hive", which will edit the user's Registry hive directly.

After saving changes to the local system-wide GPO on Home, Policy Plus mimics the signaling behavior of the real Group Policy infrastructure to ask other programs to react to the settings change. This will cause some policies to be applied immediately. However, Policy Plus cannot detect or control what other system components do in response to that signal, so a reboot or logoff/logon cycle may be necessary for those other programs to reload their policies from the Registry.

Does that clear things up?
