### ISSUE TITLE
Exporting SPOL

### ISSUE THREAD

**Issue by xaduha** [Fleex255/PolicyPlus#35]
This format looks interesting, but I'm a bit confused about how to use it properly since there is no export option for it that I can see, only import. Looked through the issues quickly, doesn't seem like it come up before. So is it just collecting various fragments in a file manually?

**Comment by Fleex255** [comment]
Right, at the moment there isn't a way to export multiple policy settings as SPOL simultaneously. That would be a good feature, though! I'll leave this open as an enhancement request.
