### ISSUE TITLE
Not all options and settings available in PolicyPlus.

### ISSUE THREAD

**Issue by Cyberdroid1** [Fleex255/PolicyPlus#36]

**Comment by Fleex255** [comment]
Hmm, what specifically seems to be missing? Note that if you're on a Home edition, you will need to use *Help | Acquire ADMX Files* once to install the full set of policy definitions.

**Comment by Cyberdroid1** [comment]
Oh, thank you so much. I did that and now I have all options. 

I would request that if there could be a feature that could detect which Windows version is on the user's PC. If it is Home edition, it will prompt the user to go through the process you told to access all policies.

**Comment by Fleex255** [comment]
Good idea. That's implemented in https://github.com/Fleex255/PolicyPlus/commit/0dc91c67cd15b7eb717921987c27a897e30648f3.
