### ISSUE TITLE
[Additional Info] Malwarebytes detects PolicyPlus as a suspicious download

### ISSUE THREAD

**Issue by dennyamarojr** [Fleex255/PolicyPlus#40]
Hi Fleex255,

Recently I start use malwarebytes and it seems that they are classify the download link of policy plus as a suspicious download

Here's a screenshot

![image](https://user-images.githubusercontent.com/36896116/107546849-a9e14c80-6b81-11eb-878c-5537fc56ba33.png)

Users are allowed to continue and download the file, if the users are using Microsoft Edge Chromium they need to click on the three dots (...) and them click keep and after that they will redirect to downloads page and them click Keep it anyway.

**Comment by Fleex255** [comment]
Thanks for the note. This happens because Policy Plus, especially the debug/dev build, isn't a super common download.
