### ISSUE TITLE
Blocking/delaying Windows feature updates?

### ISSUE THREAD

**Issue by User087** [Fleex255/PolicyPlus#41]
Can this program be used to block or delay Windows feature updates? If not, could this functionality be added?

**Comment by Fleex255** [comment]
The most promising policy setting would be "Select when Preview Builds and Feature Updates are received" (`Microsoft.Policies.WindowsUpdate:DeferFeatureUpdates`). You could probably use that to defer receiving feature updates for a month at a time. I have not tested this on Home editions, however,
