### ISSUE TITLE
"Saving failed" error

### ISSUE THREAD

**Issue by zdat** [Fleex255/PolicyPlus#44]
The error I receive is:

> Saving failed!
> 
> The type of the value object did not match the specified RegistryValueKing or the object could not be properly converted.

I receive this error after going to File > Save Policies.

Have been using this program over the past couple of months and everything has been working fine but after doing some tweaking today I received this. Could this be related to a specific policy I changed?

**Comment by Fleex255** [comment]
Apparently [`RegistryKey.SetValue`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registrykey.setvalue?view=net-5.0#Microsoft_Win32_RegistryKey_SetValue_System_String_System_Object_Microsoft_Win32_RegistryValueKind_) expects signed integers for `DWord` values, so trying to write values larger than `Int32.MaxValue` (2<sup>31</sup> - 1) produces the error you received. I added a workaround in https://github.com/Fleex255/PolicyPlus/commit/e9611602d9a2d6b48426910ce8b1c1e2a85a4002. Please try the [updated dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) to see if this fixes the problem.

**Comment by zdat** [comment]
It worked. Thank you for the very quick fixes on both of my issues. Wont leave you hanging this time... :D
