### ISSUE TITLE
Github Actions compiler

### ISSUE THREAD

**Issue by ImportTaste** [Fleex255/PolicyPlus#45]
It's been a little over a year since a new snapshot was posted in the Releases section. A lot of people have been moving over to having new snapshots compile automatically with every commit, and I think it would be rather trivial to get it set up with this project. I could probably help if need be.

**Comment by Fleex255** [comment]
Thank you for the suggestion and the offer. I will look into this. Until then, a current version can be downloaded as the "Debug" build linked in the README - I've been keeping that up to date with every commit. Once I get some time I will also do some more thorough testing to see that the newest commit is suitable for release.

**Comment by Fleex255** [comment]
I set up [a GitHub Action](https://github.com/Fleex255/PolicyPlus/actions/workflows/latest.yml) for each commit to build and publish to S3. (I'd like to reserve the Releases page for more mature, better-tested builds.) To prove that the executable published to my S3 bucket is exactly the one that was compiled from the commit, I added a "compute hash" step to the Action that records the SHA256 hash.
