### ISSUE TITLE
Filtering not working as expected?

### ISSUE THREAD

**Issue by davidtgbe** [Fleex255/PolicyPlus#48]
I'm trying to filter polcies to show only the ones that are suitable for W10.

I'm using last ADMX from W10 21H1.

Just looking for this policy for example: taskbar lockdown:

![3](https://user-images.githubusercontent.com/3966235/122795061-3aacff00-d2bd-11eb-8813-c60a32c76712.JPG)

It has a min OS requirement of Server 2003 or XP (represented as an integer value equal to 2):

![4](https://user-images.githubusercontent.com/3966235/122795538-b9a23780-d2bd-11eb-9b58-e788bfa14e8d.JPG)

If configure the filter like this:

![1](https://user-images.githubusercontent.com/3966235/122794977-1f41f400-d2bd-11eb-9b24-5dd98c9787c9.JPG)

I expect to view the before mentioned policy listed in the listview, but it is not.

![2](https://user-images.githubusercontent.com/3966235/122794973-1ea95d80-d2bd-11eb-98d3-10e6f8765e5c.JPG)

So it seems that filter is not working as expected. At least, as I expected :) 
May be I'm missing something...

**Comment by Fleex255** [comment]
Thank you for the detailed report. I can confirm that there is something wrong with the support filter. I will investigate this week when I can.

**Comment by Fleex255** [comment]
https://github.com/Fleex255/PolicyPlus/commit/a8a5bf988368054a54c9c47913b199439565f26e addresses this issue. While I was at it, I also fixed some inconveniences with that tree view in the Filter Options dialog. At your convenience, please see if the [updated dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) solves the problem.

**Comment by davidtgbe** [comment]
I was downloading your updated dev build but, my antivirus blocked it. You should check it; https://www.virustotal.com/gui/file/365f3a6ab2ab5b448444eb3a239921b2e4010b2708a6c70f961dc7a8011582b0/detection/f-365f3a6ab2ab5b448444eb3a239921b2e4010b2708a6c70f961dc7a8011582b0-1624775707

**Comment by Fleex255** [comment]
Thanks for the update! Glad it worked. 

Antivirus false positives are common for Policy Plus, especially for new dev builds which haven't had time to gain a positive reputation. Unfortunately it seems that the only reliable way to avoid this is for me to buy an expensive code signing certificate.
