### ISSUE TITLE
Possible to use with PDQ Deploy?

### ISSUE THREAD

**Issue by gitty8** [Fleex255/PolicyPlus#5]
Have someone experience to use this with PDQ Deploy / Inventory to edit GPOs for local machines on network or domain ?

**Comment by Fleex255** [comment]
I did a little reading on PDQ Deploy (since I was previously unfamiliar with it) and it looks like you could use it to replace local GPOs by creating a custom package with a file copy followed by a bit of PowerShell to invoke policy refresh. Unfortunately, per [this documentation page](https://documentation.pdq.com/PDQDeploy/15.3.0.0/index.html?package.htm) it appears that a paid version of PDQ Deploy is necessary for those step types. I'm therefore unable to test any methods, but if you have a fancy version, I'd be happy to work with you to figure out a solution.

**Comment by gitty8** [comment]
https://www.pdq.com/try/
14 days trial is possible?

**Comment by Fleex255** [comment]
Sorry for the long wait! I finally got an environment set up where I can test this, and I managed to get something working. To create the policy settings you want to deploy, use *File | Open Policy Resources* to create a POL file for both the computer and user sources. I called them `comp.pol` and `user.pol` respectively. Once you have those opened, set your policy settings as normal. After you've saved, copy the POL files and `Policy Plus.exe` to a new folder.

In PDQ Deploy, create a new package. Set its "run as" option to Local System. Add a File Copy step, with the POL-and-EXE-containing folder as the source and `$(Repository)` as the destination. In the File Patterns box, put `*.pol` and `*.exe`. (This will keep any loose CMTX files out of the way if you ever want to edit the POLs right from the deployment folder.) Add a PowerShell step with this script:

```
$repo = [System.Environment]::ExpandEnvironmentVariables("$(Repository)")
[System.Reflection.Assembly]::LoadFile("$repo\Policy Plus.exe")
$compLoader = New-Object PolicyPlus.PolicyLoader ('LocalGpo', '', $false)
$compSrc = $compLoader.OpenSource()
$compPol = [PolicyPlus.PolFile]::Load("$repo\comp.pol")
$compPol.Apply($compSrc)
$compLoader.Save()
$compLoader.Close()
$userLoader = New-Object PolicyPlus.PolicyLoader ('LocalGpo', '', $true)
$userSrc = $userLoader.OpenSource()
$userPol = [PolicyPlus.PolFile]::Load("$repo\user.pol")
$userPol.Apply($userSrc)
$userLoader.Save()
$userLoader.Close()
gpupdate
```

This script applies the deployed POL files onto the computer's local GPO. If you're only interested in one section, remove the code specific to the other. There is then no need to deploy the POL for the section you don't want.

Note that if you configure a policy, deploy, then unconfigure the policy, the configuration will probably stick. If that's a problem, or if this setup doesn't do what you're after, please let me know.
