### ISSUE TITLE
Policy Plus not downloading latest ADMX files? (and a bug?)

### ISSUE THREAD

**Issue by zdat** [Fleex255/PolicyPlus#52]
So I was making sure I had all the latest policies. I downloaded [this](https://www.microsoft.com/en-us/download/details.aspx?id=103668) from Microsoft's website to make sure I did.

It would appear policies from 21H1 and 21H2 (if you go to the "Administrative Templates" sheet on that that spreadsheet) aren't getting downloaded (or at least aren't appearing?) from Policy Plus, even when I go to "Help" > "Acquire ADMX Files"?

So I tried getting the files manually from [Microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=103667&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1) and (incorrectly?) importing them, but then I got this error that pops up whenever I open Policy Plus:

![policy](https://user-images.githubusercontent.com/59732143/160305397-91574c8b-4208-4733-b4a3-4fe1089b4a42.png)

It can't be closed and I can't get to the regular Policy Plus window. I force closed the program and deleted the directory I was trying to load the files from which fixed it.

Can some help be given as to how I get the latest policies? I assumed pressing "Acquire ADMX Files" would but it seems it isn't up to date? Thanks.

**Comment by Fleex255** [comment]
Thank you for the report. Acquire ADMX Files was indeed downloading the 20H2 package. I have updated it to download the Windows 10 **21**H2 package&mdash;please try the [latest build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusLatest.exe).

For mysterious reasons, Microsoft is *also* distributing Windows 11 ADMX files that are not a superset of any Windows 10 ADMX package. I will need to think about what to do about this, possibly provide a choice in the download dialog.

As for why manually obtaining the policy definitions didn't work: I notice that `staging_` has been prepended to the ADMX names in your screenshot. Unless the ADML files in the language-specific subdirectories were similarly renamed, that would break the association between ADMX and ADML. Unfortunately there were so many files that the Yes and No buttons went off the screen. Pressing Escape might choose "No", though I'm not sure if that always works.

**Comment by epman100** [comment]
although it's nice that the latest build of Policy Plus can download the latest ADMX Files from MS, it should be improved to detect the Windows version being run first and then download the appropriate ADMX files from MS.

I had a minor problem when running Policy Plus on a Win8.1 home system and choosing the Acquire ADMX Files option actually downloaded the ADMX/ADML package for latest Win10 version, which is not what I want and a few of those admx/adml files would not load under Win8.1 home (because those policy files are only compatible with Win10 and not any pre-Win10 version)

**Comment by Fleex255** [comment]
Thanks for the report. I agree that obtaining inapplicable policy definitions can be undesirable and it would be better to offer version-specific definitions. I've opened a new issue #55 to track this feature request.

Could you please clarify how exactly the Windows 10 definitions failed to load on Windows 8.1? Policy Plus has its own ADMX loader that should work the same regardless of host OS, so if it couldn't handle the newest definitions, that's a separate bug. But if the Local Group Policy Editor was installed on Home (an unsupported configuration) and choked on the new definitions, that's not a Policy Plus bug (but does emphasize the usefulness of getting the right definitions for the current Windows version).
