### ISSUE TITLE
DSCP setting per app?

### ISSUE THREAD

**Issue by danergo** [Fleex255/PolicyPlus#53]
Hi!

Thanks for the app, seems very nice, I'm looking for a way to set DSCP value for all traffic coming from a single application.

And while I know how to do it on "gpedig.msc" I couldn't find it in your app. Can you please help me finding it?

Note: I'm on Windows10 Home, and "gpedig.msc" is installed manually and doesn't seem applying the defined DSCP values into the packets.

**Comment by Fleex255** [comment]
I'm sorry, Policy Plus currently only supports "Administrative Templates" policies. Other types of policies involve very different mechanisms and are therefore not likely to be implemented soon.

You might try the [`New-NetQosPolicy`](https://docs.microsoft.com/en-us/powershell/module/netqos/new-netqospolicy?view=windowsserver2022-ps) PowerShell cmdlet or look around the internet for where QoS policies are stored. However, I am not sure whether Home editions will respect QoS policies no matter how they are set.
