### ISSUE TITLE
Not an issue, it's a question

### ISSUE THREAD

**Issue by tedomedo** [Fleex255/PolicyPlus#54]
Is PolicyPlus working as group policy management console too? GPMC is needed to disable defender updates.

**Comment by Fleex255** [comment]
The GPMC is for managing multiple Group Policy Objects across a domain. The settings you're looking for are very likely set within a GPO, in which case the Local Group Policy Editor can probably set them for a single computer. If they're under an Administrative Templates branch, Policy Plus will be able to see them too. (Caveat: a few policies, especially related to updates, are sometimes ignored by their target applications on non-Enterprise editions. It's worth a try, though.)

**Comment by tedomedo** [comment]
As i see on some sites, GPMC is needed to close Defender. It downloads updates every day, i don't want this. Is there any way to stop receiving updates for Defender? I have windows 10 home. I installed gpedit.msc using this site: https://www.majorgeeks.com/content/page/enable_group_policy_editor_in_windows_10_home_edition.html

**Comment by Fleex255** [comment]
Hmm, try looking through the instructions to see if they eventually ask you to navigate to something under "Administrative Templates." If so, navigate through that same subpath in Policy Plus.

Unfortunately I don't know the details of Windows Defender, so I don't know which policies you are looking for or whether Windows Defender would respect them on Home editions. (Even if Policy Plus adjusts the Registry correctly, that doesn't matter if the target application ignores the setting.)

If I remember correctly, the linked method of installing gpedit.msc produces a Local Group Policy Editor that looks right but doesn't actually apply any settings to the Registry. Nevertheless, it might be your best hope if the policy of interest is outside Administrative Templates.

**Comment by tedomedo** [comment]
So there's nothing to do in win 10 home?  Where can i find a key to get pro upgrade for free?

**Comment by Fleex255** [comment]
> So there's nothing to do in win 10 home?

Depending on what kind of policy is needed and whether Home editions' version of Defender consults it, it *might* be possible to change the behavior on Home&mdash;I'm just saying that I don't know enough about Defender specifically to say. :) Again, you can try looking ahead in the instructions you found to see if any of the folders you need to navigate through have an equivalent in the LGPE / Policy Plus. You could also try asking about the Defender configuration or Registry settings in a more general forum.

> Is there an .exe in github to disable uploads for defender?

Not that I know of, sorry. It depends again on how the policy is set and whether Defender checks it on Home editions. If the Home edition of Defender doesn't check for any such policy, no such EXE could exist. (Well, unless it somehow altered Defender itself, but at some point the side effects of the workaround are worse than the original problem.)

> Where can i find a key to get pro upgrade for free?

Home to Pro is a paid upgrade, so any free key is either ineffective here (e.g. volume activation pseudo-key) or illegal.

> And how can uninstall group policy?

Thank you for keeping record of the installation. The batch file used DISM to install several packages whose names are shown after "adding package" in your screenshot. You can probably therefore use DISM to remove the packages. **Caution!** I have not tested this, so any attempt is at your own risk. [Here is an example](https://superuser.com/a/346400/380318); I think you can change the package name after `/packagename:` and repeat for each package.
