### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by elandorr** [Fleex255/PolicyPlus#58]
I want to thank you for making this:

- in the first place
- open source
- portable, no BS installer
- non UWP trash

Microsoft sure created the worst system imaginable, but thanks to your tool it's humanly possible to export/import and deploy GPOs in a reasonable fashion. Before that, the only option was to research random sites in hopes of finding the correct registry paths. (which may or may not change 5 mins later in a forced update) A simple, clean, accessible sqlite db? Not with Microsoft.

I'm sharing this around, very underappreciated tool.

Cheers!

**Comment by Fleex255** [comment]
You're welcome! I'm glad Policy Plus is helpful for you.
