### ISSUE TITLE
unable to change the language in English

### ISSUE THREAD

**Issue by 70V07** [Fleex255/PolicyPlus#59]
**first of all: _**great program, really, its absurd Windows Home edition not have this from default._

**the problem:** _the program start in Italian but I not setup the language for PolicyPlus, and I want the prgram in English._

I not find any option to change language. my first language is Italian, but I prefer use English in programs why I find more tutorials in English using Internet search engines, if program is in Italian some names for elements are very different, and is disfunctional (the English tutorials become inapplicable to Italian program).

**Comment by Fleex255** [comment]
Please try opening *File | Set ADML Language* and setting the preferred ADML language code to `en-US`. If this doesn't help or causes errors, use *Help | Acquire ADMX Files*, which will download a full set of policies with their English descriptions.

**Comment by 70V07** [comment]
so... that setting changed the language on the program, not onto system, good to know, problem solved.
