### ISSUE TITLE
no .exe

### ISSUE THREAD

**Issue by tristanlifn** [Fleex255/PolicyPlus#61]
so as the title says there isn't a .exe file. i gownloaded the master and june 2021, and none of them had a .exe file

**Comment by Fleex255** [comment]
The Git repository is for source code. To download the compiled EXE, choose `PolicyPlus.exe` under "Assets" on [the releases page](https://github.com/Fleex255/PolicyPlus/releases), or click "download the latest build" in [the README](https://github.com/Fleex255/PolicyPlus#download).
