### ISSUE TITLE
POL vs REG for exporting and importing settings

### ISSUE THREAD

**Issue by dardoor** [Fleex255/PolicyPlus#63]
I want to use PolicyPlus instead of gpedit.msc to apply settings more quickly on a new Windows install (single user).

In that case, does it matter whether I export and import POL or REG files from and into PolicyPlus, or is the end result the same?

**Comment by Fleex255** [comment]
That depends on whether you might want to edit the new machine's policy settings further with Policy Plus / Local Group Policy Editor. Both will end up applying the settings to the Registry (which is the important part), but only POL import will let the Local Group Policy Editor see your policy settings.

**Comment by dardoor** [comment]
Are you sure? Maybe there's some misunderstanding, but here's what I did:
1. Start PP, set the desired changes, export REG file (Computer)
2. Move to a fresh Win10 install, start PP, import REG file, 'Save Policies'
Result: the policy changes are visible when I run gpedit.msc.

**Comment by Fleex255** [comment]
Ah yes, you're right: importing a REG *in Policy Plus* will apply it to the policy object. (Importing a REG with the standard Registry Editor would only update the Registry, not the policy object.) Sorry for the confusion.
