### ISSUE TITLE
I want to enable web results back!

### ISSUE THREAD

**Issue by Upsidedowncake81363** [Fleex255/PolicyPlus#64]
Hi
Due to debloating my windows 11
Web results in windows 11 got disabled
Since I am using home version
The real looking regedit is for show up
Is it possible to enable it in policy plus I cannot find it
It is in explorer in Local user, Policies.

**Comment by Fleex255** [comment]
While I cannot know exactly how destructive the "debloating" tool was, a standard way of disabling web results [seems to be](https://www.groovypost.com/howto/disable-web-search-results-on-windows-11/) the "Turn off display of recent search entries in the File Explorer search box" policy. In Policy Plus's left pane, its container is Windows Components → File Explorer. If you don't see those folders, you probably need to download policy definitions with *Help | Acquire ADMX Files* from the menu. Once you find the policy, set it to Disabled, save, and reboot.

If that doesn't work, you [might also try](https://www.ghacks.net/2021/11/26/how-to-turn-off-search-the-web-results-in-windows-11/) looking in Windows Components → Search for "Do not allow web search" and "Don't search the web or display web results in Search". They might also need to be disabled.
