### ISSUE TITLE
Policy Plus.exe detected as malicious by virus total

### ISSUE THREAD

**Issue by bob-u** [Fleex255/PolicyPlus#67]
![image](https://user-images.githubusercontent.com/61708771/235274188-b1b1b71f-43c3-401d-9a8d-af200965b6c0.png)

**Comment by Fleex255** [comment]
These are false positives, likely triggered by the ability to manipulate policy files, modify the Registry, or work with offline user hives. Just like the standard Registry Editor, you could recklessly use Policy Plus to cause problems for your computer (hence the "riskware" designation), but the tool itself isn't malicious. 

See #49 for more history with antivirus false positive detection. Unfortunately there's not much I can do to clear these detections, except possibly buying an expensive code signing certificate.

As described at the end of the README, you can check the executable hash and examine the Actions output for proof that the executable was built from a published Git commit.
