### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by rokejulianlockhart** [Fleex255/PolicyPlus#69]
My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245.

However, in the case of this repository, I'd like to ask https://github.com/Fleex255/PolicyPlus/issues/46#issuecomment-1557530975, but about whether this behaviour is correct for this project rather than Windows's `gpedit.msc`.

**Comment by Fleex255** [comment]
Yes, it seems good to distinguish discussions from bugs. I've enabled the Discussions feature.

**Comment by beedell-roke** [comment]
Thanks! I've asked [`discussions/70`](https://github.com/Fleex255/PolicyPlus/discussions/70#discussion-5233924).
