### ISSUE TITLE
The executable was found to have 4 viruses

### ISSUE THREAD

**Issue by MochaTV** [Fleex255/PolicyPlus#76]
![image](https://github.com/Fleex255/PolicyPlus/assets/128996176/0c91c761-55d8-4e32-b45f-868cc909d2ea)
Is there any chance this could be a false positive?

**Comment by Fleex255** [comment]
The hash matches the latest release build, so it is a legitimate version of Policy Plus. These are false positives. For more history, see #49 (and other duplicates #40 and #67).
