### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Neustradamus** [Fleex255/PolicyPlus#79]
Dear @Fleex255,

It is possible to create a new release?

Latest is old (2021-07-01), more two years.

We can see on https://github.com/Fleex255/PolicyPlus
June 2021 snapshot (Latest)
on Jul 1, 2021
+ 1 release

**Comment by Fleex255** [comment]
Currently there are very few functional [changes from the previous release](https://github.com/Fleex255/PolicyPlus/compare/June2021...master). Once there are more changes - I at least need to update the Microsoft ADMX download URL - I'll make a new release. If you specifically need one of the small unreleased changes, please use the latest dev build.

**Comment by eabase** [comment]
@Fleex255 
This app is too cool to be cold! 
I think you could do just a cosmetic update to show people that the project is still alive and working with W11 etc.
