### ISSUE TITLE
Request to support "Configured" as a filter state

### ISSUE THREAD

**Issue by kerframil** [Fleex255/PolicyPlus#8]
In addition to "Not Configured", I think that it would be useful to have "Configured" as a filtering option, effectively matching any policies that have been explicitly configured as either enabled or disabled.

**Comment by ThiefMaster** [comment]
That would be very useful, especially to quickly see everything I've configured (and might want to carry over to a new windows installation) over the years since I installed Windows.

**Comment by Fleex255** [comment]
Great idea! Implemented in https://github.com/Fleex255/PolicyPlus/commit/712689a16245514d16af12747bb6673daffcc9e2; the Debug build link has been updated. Please let me know whether this is what you were looking for.

**Comment by kerframil** [comment]
It certainly is. Thanks, Ben.
