### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by tyrell-wallace** [Fleex255/PolicyPlus#82]
I'm on Windows 10 22H2.

No matter what I change, nothing seems to happen. How can I test if the program is working as intended?

**Comment by Fleex255** [comment]
Please make sure you saving your changes (*File | Save Policies*) - this does not happen automatically.

To check whether a policy change is being written to the Registry, right-click a policy setting you configured and choose Element Inspector. The primarily Registry key (path) and value (entry) name affected by the policy are shown at the top. You can look at that path in the Registry Editor under HKEY_LOCAL_MACHINE (for Computer policies) or HKEY_CURRENT_USER (for User policies). If you saved and the Registry value is not being written, that is a bug.

However, if the value is written and just has no effect, it is possible that the component that applies it is missing in Home editions or the 22H2 version. In that case, please specify which policies you are trying to use.

**Comment by tyrell-wallace** [comment]
Oh, I wasn't aware I had to click on that option. I've checked it on the registry and it's working. The specific thing I enabled only went into effect after I logged off and then in again (it didn't say it was necessary though).
