### ISSUE TITLE
PowerShell execution policy not changing on win 11 home

### ISSUE THREAD

**Issue by Sushi0452** [Fleex255/PolicyPlus#84]
when i change the policy turn on script execution (in folder windows components and then in windows powershell, also im in the computer section) and i restart the computer it doesn't change. I tried to reinstall it but it still didnt work

this is where i downloaded it from:
![Screenshot_330](https://github.com/Fleex255/PolicyPlus/assets/126282613/08b458c4-106d-43dd-9fb7-37316c633825)

**Comment by Fleex255** [comment]
To troubleshoot, let's first check that the expected settings are getting applied to the Registry. If you enabled the Computer version of "Turn on Script Execution", this Registry key...

    HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\PowerShell

...should have `EnableScripts` set to 1 and `ExecutionPolicy` set to Unrestricted (if you chose "Allow all scripts") or RemoteSigned (if you chose "Allow local scripts and remote signed scripts").

![screenshot of the Registry Editor viewing the above settings](https://github.com/Fleex255/PolicyPlus/assets/4155641/68c844ed-3edc-469e-87cc-1adfa6ff4cbd)

If you don't see these Registry entries, please make sure you used *File | Save Policies* after editing the policy setting.

If you *do* see these entries, please let me know if you're using the built-in PowerShell or a newer (PowerShell Core) version you installed.
