### ISSUE TITLE
Not all policies are listed. Discovered this while attempting to remove Copilot.

### ISSUE THREAD

**Issue by Amariithynar** [Fleex255/PolicyPlus#85]
The instructions for disabling copilot are as follows:
Group Policy Editor > User Configuration > Administrative Templates > Windows Components > Windows Copilot > Turn off Windows Copilot

However, using PolicyPlus, there is no option for Administrative Templates. In the options that are available (and yes, I did re-acquire ADMX files) there is also no option for Windows Copilot.

This is not the first time I have noticed that not all policies are actually being listed, either, but previously it was not a major concern to me. This, however, is.

**Comment by Fleex255** [comment]
Policy Plus currently only supports Administrative Templates, so the entire left tree is the contents of Administrative Templates - for example, Windows Components should be there at the top level.

Due to the split between Windows 10 and Windows 11 policy definitions, there currently isn't a way to get *all* policies for every OS version (issue #55). This sounds like a Windows 11-specific policy, so you can try downloading and unpacking [the latest Windows 11 ADMX files](https://www.microsoft.com/en-us/download/details.aspx?id=104593), then using *File | Open ADMX Folder* to load them into Policy Plus.

**Comment by ericvenneker** [comment]
Windows 11 23H2 policy definitions can be downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=105667

The policy should definitely be in there:

![image](https://github.com/Fleex255/PolicyPlus/assets/24191832/a8cc9f7a-b5a9-4867-b811-86c0b3575459)

**Comment by Amariithynar** [comment]
> Windows 11 23H2 policy definitions can be downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=105667
> 
> The policy should definitely be in there:
> 
> ![image](https://user-images.githubusercontent.com/24191832/284026209-a8cc9f7a-b5a9-4867-b811-86c0b3575459.png)

Unfortunately as you can see, even using "Acquire ADMX Files" and then following it up by downloading the administrative template MSI and installing them all to the same PolicyDefinitions folder within Windows then refreshing PolicyPlus to use said folder, even after a restart: it does not, for me. Maybe there's something else that I am just not seeing?
![image](https://github.com/Fleex255/PolicyPlus/assets/22435375/619fc405-3ec2-4f87-a8da-473efd5c6d0e)

**Comment by Fleex255** [comment]
This policy is defined in `WindowsCopilot.admx`. Please check if that file exists *directly* inside your PolicyDefinitions folder. (You can also check *View | Loaded ADMX Files* to see if Policy Plus has detected it.) If it's not there, try extracting the 23H2 policy definitions again and use *File | Open ADMX Folder* to load them.

**Comment by Amariithynar** [comment]
> This policy is defined in `WindowsCopilot.admx`. Please check if that file exists _directly_ inside your PolicyDefinitions folder. (You can also check _View | Loaded ADMX Files_ to see if Policy Plus has detected it.) If it's not there, try extracting the 23H2 policy definitions again and use _File | Open ADMX Folder_ to load them.

Mhm, and that's the problem. That file does not exist and does not install no matter how many times I use the MSI to install the latest 23H2 policy definitions or run PolicyPlus' internal ADMX acquire function.
