### ISSUE TITLE
Add secpol.msc policies

### ISSUE THREAD

**Issue by Dragodraki** [Fleex255/PolicyPlus#88]
Could you add the security group policies from secpol.msc to your app please? Currently it's limited to pure group based policies. If you open the native gpedit.msc it provides elements from secpol.msc too though. 

It would be so much easier to have all possible policies in one app.

**Comment by Fleex255** [comment]
This would be nice eventually. It's just a lot of effort due to how different Security Policies are from Administrative templates. Please follow #20 for updates.
