### ISSUE TITLE
Can you make a new release

### ISSUE THREAD

**Issue by linzhongzi** [Fleex255/PolicyPlus#89]
Would it be possible to make a new Release distribution package. I don't have a VB compiler and can't do it myself. The main thing is that I would like to have two modules, Software Settings and Windows Settings. But for the 2021 version, there is only one module, Administrative Templates.

**Comment by Fleex255** [comment]
Software Settings and Windows Settings work very differently than Administrative Templates, so a lot of new implementation work will be needed to support them - it's not as simple as running a new build. Please follow #20 for any progress on supporting Windows Settings.
