### ISSUE TITLE
Any disadvantages compared to gpedit.msc?

### ISSUE THREAD

**Issue by ThiefMaster** [Fleex255/PolicyPlus#9]
I'm using Win7 / Win10 pro, so I could just use gpedit.msc. However, it's UI is absolutely awful and wasn't updated in more than a decade - I'm missing the simple things, like searching by name or the UI resizing when resizing the window (the default window size is tiny..)

So I'm curious, do I have any drawbacks when using PP instead of the original gpedit.msc?

**Comment by Fleex255** [comment]
For use with ADMX-based policies on a standalone computer, I think Policy Plus's functionality is a strict superset of the LGPE's. (In fact, on Pro editions, Policy Plus delegates to the official Group Policy infrastructure to apply POL data to the Registry.) The only difference I can think of is that Policy Plus writes Registry entries to the POL file in alphabetical order, but that shouldn't matter at all unless some intense manual tuning is going on. 

You would still need the LGPE (and/or other MMC snap-ins like Local Security Policy, `secpol.msc`) to change settings outside of Administrative Templates, and you would still use the standard Group Policy tools to work with GPOs in Active Directory. Currently I'm focusing on ADMX-based policies on standalone machines, but there's always the possibility of branching out in the future!

I hope this answers your question. If there's anything I can clarify, please let me know. Thanks for your interest in Policy Plus!
