### ISSUE TITLE
PolicyPlus not working

### ISSUE THREAD

**Issue by Kruk101** [Fleex255/PolicyPlus#91]
I just few days ago upgraded from Windows 10 to 11Home on an unsupported laptop and tried to install Group Policy Editor. I found a script on the internet and installed it, but it didn't work. Then I found a video about Policy Plus and installed the app. As a test, I tried the
"remove all elements from desktop", hit apply, OK, restarted the computer and it didn't work. Tried this twice more, with the same result.
Can anyone help me with this?

**Comment by Fleex255** [comment]
I haven't tried with this particular policy on Windows 11 Home, but can you please first make sure you've used *File | Save Policies* after changing the setting?

I agree that this behavior is confusing. Issue #51 is pending to improve this.

**Comment by Kruk101** [comment]
I was missing some files, after downloading them it works.
