### ISSUE TITLE
Live project or abandoned?

### ISSUE THREAD

**Issue by incansvl** [Fleex255/PolicyPlus#92]
I just discovered PolicyPlus and was hopeful that it would provide me with a tool for managing folder redirection policies on both Windows Home and Pro systems.

However I can find no user-level documentation, how-to's or examples, so i'm left floundering in the dark. The policy object tree that P+ shows is unlike the one shown in examples that use the Microsoft Group Policy Management Console, so examnples from that application aren't helpful, and just searching P+ for items with names that include "redirect", "Documents" etc. don't seem to show up anything relevant, so I am not sure how to proceed.

Theh I realised this repo has not had any commits since 2021. So is the tool abanconed now, and even if it is, is there any source of information on how to use it while it still runs (on Win 10)?

**Comment by Fleex255** [comment]
At the moment I am only making sure there are no major functionality bugs. New features are not currently being developed.

Only policies under the Administrative Templates branch are currently supported. Other policies like folder redirection work very differently and would need significant new effort to support. That is not likely to happen in the near future, sorry.

For how to use the program, please start with the "quick intro" section of the README. The core features that match the official Local Group Policy Editor should work very similarly. Please let me know if I can clarify anything.

**Comment by incansvl** [comment]
That's unfortunate. I don't know enough about Group Policies to understand why folder redirection is a different animal to "Administrative templates" but have to accept the explanation. I appreciate the rapid and clear reponse. Thank you.
